projects:
  Nick-numeric-values-app-AppSync:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/API.service.ts
        docsFilePath: src/graphql
        region: eu-central-1
        apiId: d3sicduvgzfipljlrkoqx64qmu
        maxDepth: 2
extensions:
  amplify:
    version: 3
